# @package _global_

wrapper:
  _target_: agents.taco_wrapper.TACOWrapper
  encoder_lr: ${encoder_lr}
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  reward: ${reward}
  multistep: ${multistep}
  latent_a_dim: none
  curl: ${curl}
  pretrained_path: ${pretrained_path}
  freeze_encoder: ${freeze_encoder}
  no_enc_auxiliary_losses: false
  optimizer_type: adam


