# @package _global_
agent:
  _target_: agents.ddpg.DDPGAgent
  reward_free: ${reward_free}
  obs_type: ${obs_type}
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: 1e-4
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  use_wandb: ${use_wandb}
  num_expl_steps: 2000 
  hidden_dim: 1024
  feature_dim: 50
  stddev_schedule: 0.2
  stddev_clip: 0.3
  nstep: 3
  batch_size: 1024 # 256 for pixels
  init_critic: true
  pretrained_path: ${pretrained_path}
  load_encoder: true
  load_actor: false
  load_critic: false 
  freeze_encoder: ${freeze_encoder}